spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
      baseline-on-migrate: true
      schemas: migrations
      locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug